name: burma-automaton
base: core24
version: '1.0.0'
summary: AI-powered 3D world generator for robotics simulation
description: |
  Burma Automaton is an AI-powered tool for generating 3D simulation worlds
  using natural language. It uses Microsoft's BitNet.cpp for efficient 1.58-bit
  LLM inference to create Gazebo-compatible world descriptions.

  Features:
  - Natural language to 3D world conversion
  - BitNet.cpp integration (1.58-bit efficient inference)
  - Gazebo SDF export
  - RViz map conversion
  - Material and lighting management

title: Burma Automaton
license: MIT
contact: https://github.com/leo007-htun/Burma_Automaton/issues
website: https://github.com/leo007-htun/Burma_Automaton
source-code: https://github.com/leo007-htun/Burma_Automaton
issues: https://github.com/leo007-htun/Burma_Automaton/issues

grade: stable
confinement: strict

platforms:
  amd64:

apps:
  burma-automaton:
    command: usr/bin/BurmaAutomaton
    plugs:
      - home
      - network
      - opengl
      - desktop
      - desktop-legacy
      - wayland
      - x11
    environment:
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt6/plugins
      QT_QPA_PLATFORM: xcb   # or 'wayland' if using Wayland
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/libproxy:$LD_LIBRARY_PATH
      BURMA_BITNET_CLI: $SNAP/usr/local/bin/llama-cli
      BURMA_BITNET_MODEL: $SNAP/usr/share/burma-automaton/models/ggml-model-i2_s.gguf


parts:
  burma-automaton:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - build-essential
      - cmake
      - qt6-base-dev
      - libqt6opengl6-dev
      - libqt6openglwidgets6
      - qt6-base-dev-tools
      - libcurl4-openssl-dev
      - libgl-dev
      - libglx-dev
    stage-packages:
      - qt6-qpa-plugins
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - libqt6opengl6
      - libqt6openglwidgets6
      - libqt6network6
      - libqt6dbus6
      - libxcb-xinerama0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb-xkb1
      - libxcb-cursor0
      - libxcb-util1
      - libxcb1
      - libx11-6
      - libx11-xcb1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libgl1
      - libglx0
      - libglvnd0
      - libglu1-mesa
      - libdbus-1-3
      - libfontconfig1
      - libfreetype6
      - libxrender1
      - libxi6
      - libsm6
      - libice6


  bitnet:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/burma-automaton
      echo "BitNet.cpp model will be downloaded on first run" > $SNAPCRAFT_PART_INSTALL/usr/share/burma-automaton/README.txt
